version: '2'
services:
  api:
    image: $EE_BOOK_API_IMAGE
    build:
      context: .
      dockerfile: ./dockerfiles/dev/Dockerfile
    entrypoint: [python, manage.py]
    command: [runserver] 
    volumes:
      - .:/src
    depends_on:
      - db
    ports:
      - "$EEBOOK_API_WEB_PORT:5000"
    env_file:
      - envs/local.env
    environment:
      - ENV="development"
  db:
    image: $POSTGRES_IMAGE
    ports:
      - "5432"
    env_file:
      - envs/local.env
