version: '2'
services:
  api:
    image: $EE_BOOK_API_IMAGE
    build:
      context: .
      dockerfile: ./dockerfiles/dev/Dockerfile
    entrypoint: [python, manage.py]
    command: [hello] 
    volumes:
      - .:/src
    depends_on:
      - db
    ports:
      - "$WEB_PORT:80"
    environment:
      - DB_HOST=db
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=5432
    env_file:
      - envs/local.env
  shell:
    image: $EE_BOOK_API_IMAGE
    entrypoint: [sh]
    volumes:
      - .:/src
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=5432
    env_file:
      - envs/local.env
    tty:
      true
  db:
    image: $POSTGRES_IMAGE
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
